# Project information
site_name: VcRedist
site_url: https://vcredist.com
site_author: Aaron Parker
site_description: >-
  A PowerShell module for lifecycle management of the Microsoft Visual C++ Redistributables.

# Repository
repo_name: aaronparker/vcredist
repo_url: https://github.com/aaronparker/vcredist
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2025 Aaron Parker

# Configuration
theme:
  name: material

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  #icon:
    #logo: logo
  logo: assets/images/visualstudiologo2019-256.png

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
  - social:
      cards: true
      cards_color:
        fill: "#7e56c2"
        text: "#FFFFFF"
      cards_font: Roboto

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aaronparker
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/stealthpuppy
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/aaronedwardparker/
  generator: true

# Page tree
nav:
  - Getting started:
    - Introduction: index.md
    - Included Redistributables: versions.md
    - Supported platforms: supported.md
    - Quick install: quick.md
    - Installing VcRedist: install.md
    - Get the VcRedist list: get-vclist.md
    - Download the Redistributables: save-vcredist.md
    - Export the Manifest: export-vcmanifest.md
    - More:
      - Known issues: issues.md
      - Changelog: changelog.md
      - VcRedist versioning: versioning.md
  - Windows:
    - Install the Redistributables: install-vcredist.md
    - Get the Installed Redistributables: get-installedvcredist.md
    - Uninstall the Redistributables: uninstall-vcredist.md
  - Microsoft Deployment Toolkit:
    - Import Redistributables into MDT: import-vcmdtapplication.md
    - Create a Redistributables bundle in MDT: new-vcmdtbundle.md
    - Update Redistributables in MDT: update-vcmdtapplication.md
    - Update the Redistributables bundle in MDT: update-vcmdtbundle.md
  - ConfigMgr:
    - Import Redistributables into ConfigMgr: import-vcconfigmgrapplication.md
  - Intune:
    - Import Redistributables into Intune: import-vcintuneapplication.md
    - Query Intune for Redistributables: get-vcintuneapplication.md
    - Remove Redistributables from Intune: remove-vcintuneapplication.md
  - Module help:
    - en-US:
      - about_VcRedist: help/en-US/about_VcRedist.md
      - Get-VcList: help/en-US/Get-VcList.md
      - Save-VcRedist: help/en-US/Save-VcRedist.md
      - Export-VcManifest: help/en-US/Export-VcManifest.md
      - Get-InstalledVcRedist: help/en-US/Get-InstalledVcRedist.md
      - Import-VcConfigMgrApplication: help/en-US/Import-VcConfigMgrApplication.md
      - Import-VcMdtApplication: help/en-US/Import-VcMdtApplication.md
      - Import-VcIntuneApplication: help/en-US/Import-VcIntuneApplication.md
      - Install-VcRedist: help/en-US/Install-VcRedist.md
      - New-VcMdtBundle: help/en-US/New-VcMdtBundle.md
      - Uninstall-VcRedist: help/en-US/Uninstall-VcRedist.md
      - Update-VcMdtApplication: help/en-US/Update-VcMdtApplication.md
      - Update-VcMdtBundle: help/en-US/Update-VcMdtBundle.md
      - Test-VcListUri: help/en-US/Test-VcListUri.md
  - stealthpuppy.com: https://stealthpuppy.com/
  - PSPackageFactory: https://stealthpuppy.com/packagefactory/
