name: Run PSScriptAnalyzer

on:
  push:
    paths:
      - 'VcRedist/**'
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'VcRedist/**'
  workflow_dispatch:

jobs:
  psscriptanalyzer:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Run PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run PSScriptAnalyzer (development push)
        uses: microsoft/psscriptanalyzer-action@6b2948b1944407914a58661c49941824d149734f
        with:
          path: "./VcRedist"
          recurse: true
          settings: "./.rules/PSScriptAnalyzerSettings.psd1"
          output: results.sarif

      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
